/**
 * Dynamic Environment Configuration
 * 
 * This file will be auto-generated when you run the CLI tool.
 * For now, it provides a default SINGLE/SINGLE configuration.
 */

import * as dotenv from 'dotenv';
import * as path from 'path';

// Load .env file first to get TEST_ENV
dotenv.config();

// Determine environment from TEST_ENV variable
const env = process.env.TEST_ENV || 'development';
const envFile = env === 'dev' ? 'development' : env;

// Load environment-specific .env file (will override if different)
dotenv.config({ path: path.resolve(process.cwd(), `.env.${envFile}`), override: true });

/**
 * Default configuration for SINGLE architecture + SINGLE auth
 * This will be regenerated by the CLI based on your Postman collection
 */
export const config = {
  env,
  timeout: 30000,
  baseUrl: process.env.BASE_URL || '',
  authToken: process.env.AUTH_TOKEN || '',
  services: {} as Record<string, string>,
  auth: {} as Record<string, string>,
  ssl: {
    enabled: false,
    certPath: path.resolve(__dirname, '../../../certs/client-cert.pem'),
    keyPath: path.resolve(__dirname, '../../../certs/client-key.pem'),
    caPath: path.resolve(__dirname, '../../../certs/ca-cert.pem'),
  },
};

/**
 * Get the current environment configuration
 * @returns The configuration object
 */
export const getConfig = () => config;